#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorTarget(rightMotor, 1739, 50);
	setMotorTarget(leftMotor, 1739, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

}
