#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	setMotorTarget(rightMotor, 50, 50);
	setMotorTarget(leftMotor, 50, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	delay(500);

	setMotorTarget(rightMotor, -170, 50);
	setMotorTarget(leftMotor, 170, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);


}
