#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(getUSDistance(sonarSensor) <= 50){
		setMotorSpeed(leftMotor, -50);
		setMotorSpeed(rightMotor, -50);
	}

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	//waitUntilMotorStop(leftMotor);
	//waitUntilMotorStop(rightMotor);


}
