#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	//setMotorTarget(armMotor, 90, 50);
	//waitUntilMotorStop(armMotor);

	setMotorTarget(rightMotor, 1023, 50);
	setMotorTarget(leftMotor, 1023, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	delay(500);

	setMotorTarget(armMotor, -360, 50);
	delay(500);

	setMotorTarget(rightMotor, -1023, 50);
	setMotorTarget(leftMotor, -1023, 50);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	delay(500);

	waitUntilMotorStop(armMotor);

}
