#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// starting position A
	while(getColorName(colorSensor) == colorBlack){
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);

	// starting position B
	while(getColorName(colorSensor) != colorBlack){
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	}

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);

}
