#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 50);

	while(getUSDistance(sonarSensor) > 75){
		setLEDColor(ledOff);
	}

	while(getUSDistance(sonarSensor) <= 75 && getUSDistance(sonarSensor) > 50){
		setLEDColor(ledGreen);
	}

	while(getUSDistance(sonarSensor) <= 50 && getUSDistance(sonarSensor) > 25){
		setLEDColor(ledOrange);
	}

	while(getUSDistance(sonarSensor)<= 25){
		setLEDColor(ledRed);
	}

	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);




}
